force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Pedido</label>
    <nameField>
        <label>Nome de Pedido</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pedidos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Pedidos</relationshipLabel>
    <relationshipName>Pedidos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/ModoDePagamento__c.field-meta.xml
<CustomField>
    <fullName>ModoDePagamento__c</fullName>
    <label>Modo de Pagamento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cartão</fullName>
            </value>
            <value>
                <fullName>PIX</fullName>
            </value>
            <value>
                <fullName>Vale Refeição/Vale Alimentação</fullName>
            </value>
            <value>
                <fullName>Dinheiro</fullName>
            </value>
            <value>
                <fullName>Voucher</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rascunho</fullName>
                <default>true</default>
                <label>Rascunho</label>
            </value>
            <value>
                <fullName>Aprovado</fullName>
            </value>
            <value>
                <fullName>Em viagem</fullName>
            </value>
            <value>
                <fullName>Entregue</fullName>
            </value>
            <value>
                <fullName>Pagamento Pendente</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/ValorTotalPedido__c.field-meta.xml
<CustomField>
    <fullName>ValorTotalPedido__c</fullName>
    <label>Valor Total do Pedido</label>
    <summarizedField>OrderItem__c.valorItem__c</summarizedField>
    <summaryForeignKey>OrderItem__c.Pedido__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/OrderItem__c/OrderItem__c.object-meta.xml
<CustomObject>
    <label>Item do Pedido</label>
    <nameField>
        <label>Nome de Item do Pedido</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Itens do Pedido</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OrderItem__c/fields/Pedido__c.field-meta.xml
<CustomField>
    <fullName>Pedido__c</fullName>
    <label>Pedido</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Itens do Pedido</relationshipLabel>
    <relationshipName>Itens_do_Pedido</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OrderItem__c/fields/Produto__c.field-meta.xml
<CustomField>
    <fullName>Produto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Itens do Pedido</relationshipLabel>
    <relationshipName>Itens_do_Pedido</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem__c/fields/valorItem__c.field-meta.xml
<CustomField>
    <fullName>valorItem__c</fullName>
    <label>Valor do Item</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/precoMoeda__c.field-meta.xml
<CustomField>
    <fullName>precoMoeda__c</fullName>
    <label>Preço</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/OrderController.cls
public with sharing class OrderController {
    @AuraEnabled(cacheable=true)
    public static List<Product2> getProducts() {
        return [SELECT Id, Name, precoMoeda__c FROM Product2 WHERE IsActive = true];
    }

    @AuraEnabled
    public static void saveOrder(Map<String, Object> orderDetails) {
        Order__c order = new Order__c();
        order.AccountId__c = (String) orderDetails.get('accountId');
        order.ModoDePagamento__c = (String) orderDetails.get('paymentMode');
        order.Status__c = 'Esperando Pagamento';
        //order.ValorTotalPedido__c = (Decimal) orderDetails.get('totalValue');
        insert order;

        List<OrderItem__c> orderItems = new List<OrderItem__c>();
        List<Map<String, Object>> items = (List<Map<String, Object>>) orderDetails.get('items');
        for (Map<String, Object> item : items) {
            OrderItem__c orderItem = new OrderItem__c();
            orderItem.Pedido__c = order.Id;
            orderItem.Produto__c = (String) item.get('productId');
            orderItem.valorItem__c = (Decimal) item.get('unitPrice');
            orderItems.add(orderItem);
        }
        insert orderItems;

        if (order.ModoDePagamento__c == 'Cartão') {
            order.Status__c = 'Aprovado';
            update order;
        }
    }
}